spring.application.name=sistemaincidencias

# Base de datos. Ajustar estos valores segun el entorno local.
spring.datasource.url=jdbc:postgresql://localhost:5432/sistemaincidencias
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Auth/JWT. Cambiar el secreto en produccion.
app.security.jwt.secret=EfnkA0GmTbfdFN7059H1OG+hV7fcRYpJhWGeczCFRKM=
app.security.jwt.expiration-minutes=120
